drop extension if exists "pg_net";

create type "public"."FLAVOURS" as enum ('Chocolate Chip', 'Oreo', 'Biscoff', 'Birthday Cake');

create type "public"."SIZE" as enum ('Regular', 'Small', 'Large');

create type "public"."STATUS" as enum ('Pending', 'Confirmed', 'Delivered');


  create table "public"."order_items" (
    "id" bigint generated by default as identity not null,
    "order_id" bigint not null,
    "flavour" public."FLAVOURS" not null default 'Chocolate Chip'::public."FLAVOURS",
    "quantity" bigint not null,
    "size" public."SIZE" not null default 'Regular'::public."SIZE"
      );


alter table "public"."order_items" enable row level security;


  create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "buyer" character varying not null,
    "date_order_created" date not null,
    "date_order_due" date not null,
    "total_revenue" double precision not null default '0'::double precision,
    "customization" text,
    "status" public."STATUS" not null default 'Pending'::public."STATUS",
    "instagram_handle" text not null
      );


alter table "public"."orders" enable row level security;

CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

alter table "public"."order_items" add constraint "order_items_pkey" PRIMARY KEY using index "order_items_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."order_items" add constraint "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."order_items" validate constraint "order_items_order_id_fkey";

create or replace view "public"."flavours_view" as  SELECT unnest(enum_range(NULL::public."FLAVOURS")) AS flavour;


grant delete on table "public"."order_items" to "anon";

grant insert on table "public"."order_items" to "anon";

grant references on table "public"."order_items" to "anon";

grant select on table "public"."order_items" to "anon";

grant trigger on table "public"."order_items" to "anon";

grant truncate on table "public"."order_items" to "anon";

grant update on table "public"."order_items" to "anon";

grant delete on table "public"."order_items" to "authenticated";

grant insert on table "public"."order_items" to "authenticated";

grant references on table "public"."order_items" to "authenticated";

grant select on table "public"."order_items" to "authenticated";

grant trigger on table "public"."order_items" to "authenticated";

grant truncate on table "public"."order_items" to "authenticated";

grant update on table "public"."order_items" to "authenticated";

grant delete on table "public"."order_items" to "service_role";

grant insert on table "public"."order_items" to "service_role";

grant references on table "public"."order_items" to "service_role";

grant select on table "public"."order_items" to "service_role";

grant trigger on table "public"."order_items" to "service_role";

grant truncate on table "public"."order_items" to "service_role";

grant update on table "public"."order_items" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";


  create policy "Allow deletes for all"
  on "public"."order_items"
  as permissive
  for delete
  to public
using (true);



  create policy "Allow update"
  on "public"."order_items"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Public insert order items"
  on "public"."order_items"
  as permissive
  for insert
  to public
with check (true);



  create policy "Public select order items"
  on "public"."order_items"
  as permissive
  for select
  to public
using (true);



  create policy "Allow deletes for all"
  on "public"."orders"
  as permissive
  for delete
  to public
using (true);



  create policy "Allow update for admin"
  on "public"."orders"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Public insert orders"
  on "public"."orders"
  as permissive
  for insert
  to public
with check (true);



  create policy "Public select orders"
  on "public"."orders"
  as permissive
  for select
  to public
using (true);



